### ISSUE TITLE
启动参数

### ISSUE THREAD

**Issue by avboy1337** [doorbash/ssr-client#3]
"D:\netch-1.9.4\Netch\bin\x64\Release\bin\ShadowsocksR.exe" -s 116.192.167.10 -p 9880 -k 1hecCU -m rc4-md5 -t 120 -O origin -o http_simple -g download.windowsupdate.com -b 127.0.0.1 -l 2801 -u
使用netch的时候，多出两个参数，分别是
-t
启动延时
-g
download.windowsupdate.com
该软件也是使用的ShadowsocksR-libev
最后一个-u不知啥意思
目前只有老哥这个go写的，最靠近原始ssr的参数了。
求老哥可以补充上这两个参数。

**Comment by doorbash** [comment]
@avboy1337 There is a `[-t <timeout>]             socket timeout in seconds`
for `-t` in https://github.com/shadowsocksrr/shadowsocksr-libev
but nothing for `-g`
What does `-g` option do exactly?

**Comment by avboy1337** [comment]
dear doorbash
i think -g is used for fake stream of something . for my computer , when using -g , it is likely download something from download.windowsupdate.com , inorder to looks like a normal stream from microsoft to avoid being detected.
i will try to make a deeper description

**Comment by avboy1337** [comment]
> @avboy1337 There is a `[-t <timeout>] socket timeout in seconds` for `-t` in https://github.com/shadowsocksrr/shadowsocksr-libev but nothing for `-g` What does `-g` option do exactly?

dear doorbash
i think -g is used for fake stream of something . for my computer , when using -g , it is likely download something from download.windowsupdate.com , inorder to looks like a normal stream from microsoft to avoid being detected.
i will try to make a deeper description

**Comment by doorbash** [comment]
@avboy1337 so `obfs_param` is already supported with option `--op`
`-t` is not supported maybe we can add it in the future. 
for a workaround for your problem you can edit `main.go` and change options the way you want then build it yourself.

for example:
https://github.com/doorbash/ssr-client/blob/9c6db431e940c3c2ff3b34e4e2d23ad6a4a70db5/main.go#L19

should be changed to:
```
ObfsParam      string `short:"g" description:"obfs param" required:"false"`
```

**Comment by avboy1337** [comment]
> @avboy1337 so `obfs_param` is already supported with option `--op` `-t` is not supported maybe we can add it in the future. for a workaround for your problem you can edit `main.go` and change options the way you want then build it yourself.
> 
> for example:
> 
> https://github.com/doorbash/ssr-client/blob/9c6db431e940c3c2ff3b34e4e2d23ad6a4a70db5/main.go#L19
> 
> should be changed to:
> 
> ```
> ObfsParam      string `short:"g" description:"obfs param" required:"false"`
> ```

really 3ks for your help !
