### ISSUE TITLE
dear master , argument of -u please , if possible wish can added.

### ISSUE THREAD

**Issue by avboy1337** [doorbash/ssr-client#4]
[-u]                       Enable UDP relay.
       [-U]                       Enable UDP relay and disable TCP relay.

**Comment by doorbash** [comment]
Hi @avboy1337 
Is there any particular use case that you need this option for?
`udp relay` is always enabled in `ssr-client`

**Comment by avboy1337** [comment]
dear bro
you know shadosocksr-libev is stoped, there is not going to be an ideal ssr written in go or rust  to act like before.
and i really think this repo is going to be hot .
