### ISSUE TITLE
error

### ISSUE THREAD

**Issue by avboy1337** [doorbash/ssr-client#5]
ssr-client -s 1.1.1.1 -p 1111 -k 1111 -r 1111 -m rc4-md5 -O origin -o http_simple -op download.windowsupdate.com -b 0.0.0.0 -l 2801 -f 127.0.0.1:1080

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x600213]

goroutine 1 [running]:
main.NewSSRClient({0xc0000aa090, 0x7}, 0x0, {0xc0000aa1b0, 0x7}, 0x0, 0x60, {0xc0000aa0d0, 0x4}, {0xc0000aa110, ...}, ...)
        D:/ssr-client/ssr_client.go:72 +0x873
main.main()
        D:/ssr-client/main.go:35 +0x1cf

**Comment by doorbash** [comment]
Hi @avboy1337 I'm not able to reproduce it here. would you run 
https://github.com/doorbash/bridge
and paste the output here.
You need to edit `main.go` first based on your config.

**Comment by avboy1337** [comment]
dear bro:
exe is download from the latest release:

https://user-images.githubusercontent.com/5463104/144071079-ef84cca6-b7ba-430e-a626-e1898a4ba780.mp4

**Comment by doorbash** [comment]
It's `--op` not `-op`!

**Comment by avboy1337** [comment]
> It's `--op` not `-op`!

sorry bro ,its my fault!!
